> ## Tarea 2: (Usando notebook de jupyter)** 
> ### Fecha de entrega: Septiembre 3, hasta las 5:50 pm
> - Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
> 	- Expected Output:\\
> 	- Original List: [12.23, 13.32, 100, 36.32]\\
> 	- One-dimensional numpy array: [ 12.23 13.32 100. 36.32] 

In [4]:
import numpy as np 

In [5]:
x = [12.23, 13.32, 100, 36.32]
np.array(x)

array([ 12.23,  13.32, 100.  ,  36.32])

> - Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [7]:
z = np.zeros(10)
z[6] = 11
print(z)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


> - Write a Python program to create a array with values ranging from 12 to 38.

In [8]:
x = np.arange(12,38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


> - Write a Python program to reverse an array (first element becomes last).

In [9]:
x = x[::-1]
print(x)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


> - Write a Python program to create a 2d array with 1 on the border and 0 inside.
>     
>     Expected Output:
> 	- Original array:
> 	$$
     \begin{pmatrix} 
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.
     \end{pmatrix}
    $$
> 	1 on the border and 0 inside in the array
     $$
     \begin{pmatrix} 
     1. &1.& 1.& 1.& 1.\\
     1. &0& 0& 0& 1.\\
     1. &0& 0& 0& 1.\\
     1. &0& 0& 0& 1.\\
     1. &1.& 1.& 1.& 1.
     \end{pmatrix}
    $$

In [15]:
x = np.ones((5,5))
x[1:4,1:4] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


> - Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern
> 
> 	- Checkerboard pattern:
>     $$
     \begin{pmatrix} 
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0
     \end{pmatrix}
     $$
> 	- **Hint** Explore the use of $x[a::b,::c] = d,	x[::e,f::g] = h$, where the letters are integer numbers.

In [23]:
x = np.zeros((8,8),dtype =int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


- Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.
>     - Sample Array [0, 12, 45.21 ,34, 99.91]  
>     - Expected Output:
>     - Values in Fahrenheit degrees: [0.0 12.0 45.21 34.0 99.91]
>     - Values in Centigrade degrees: [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778].
> 	- *Use functions and list comprehension* read the link https://www.pythonforbeginners.com/lists/list-comprehensions-in-python/, to additional information about of list comprehension in python.

In [6]:
celsius = np.array([0, 37.9, 21, 7, 45])
into_farenheit = lambda x: x*(9/5)+32
farenheit = [into_farenheit(i) for i in celsius]
farenheit

[32.0, 100.22, 69.80000000000001, 44.6, 113.0]

> - Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.
> 	- Expected Output:
> 	- Array1: [ 0 10 20 40 60 80]
> 	- Array2: [10, 30, 40, 50, 70, 90]
> 	- Set difference between two arrays: [ 0 20 60 80] 
> 	- **Hint**: explore the use of function *np.setdiff1d*.
> - Write a Python program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
> 

In [7]:
array1 = np.array([0,10,20,40,60,80])
array2= np.array([10,30,40,50,70,90])
np.setdiff1d(array1,array2,assume_unique=False)



array([ 0, 20, 60, 80])

> - Write a Python program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.


In [15]:
mtrx = np.zeros([4,4])
mtrx

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
    diag = lambda x,y, value: value if x == y else 0
diag_array=np.array([4,5,6,8])
for i in range(4):
        for j in range(4):
            mtrx[i,j] = diag(i,j,diag_array[i])
           
mtrx        

array([[4., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 6., 0.],
       [0., 0., 0., 8.]])